# Generated by Django 5.0.7 on 2025-02-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
