# Generated by Django 5.0.7 on 2025-02-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_objectdetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectDetection',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
